development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cerberus
  pool: 20
  timeout: 5000
  host: localhost
  username: $DB_USER
  password: $DB_PASSWORD
  socket: /tmp/mysql.sock
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cerberus
  pool: 20
  timeout: 5000
  host: localhost
  username: $DB_USER
  password: $DB_PASSWORD
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: cerberus
  pool: 30
  timeout: 5000
  host: localhost
  username: $DB_USER
  password: $DB_PASSWORD
  socket: /tmp/mysql.sock
